### PR TITLE
Update utils.py

### PR DESCRIPTION
**Pull request by camilt**
Fixed download file

### CODE REVIEW

**Comment by dobbelina** [comment]
Wow, just awesome with the livestream d/l option!
Thanks!

**Comment by dobbelina** [comment]
camilt,you should have been sent an invite from "Just to talk - future of uwc"
Please accept it and join the discussion.

**Comment by camilt** [comment]
I have accepted it, I read all the comments, but I stayed in the "shadow"

**Comment by dobbelina** [comment]
Ok, i see.
Don't know if you seen it, but i made a ffmpeg utility myself for downloading,
https://github.com/dobbelina/repository.dobbelina/issues/71

**Pull request merged**
