### PR TITLE
xhamster: add quality and duration selectors

### PR DESCRIPTION
**Pull request by kuwanishi**

### CODE REVIEW

**Comment by dobbelina** [comment]
Awesome, thanks!

**Comment by imurreflection** [comment]
Hi Kuwanishi, can you please advise how to use these search filter on any keyword. I tried but it does not work. Is it applicable only on main content? It could have been quite useful if it can filter any search content.

**Comment by kuwanishi** [comment]
As you say, it only works on the main content. I will look into adding it to the other listings too when I have some time.

**Comment by imurreflection** [comment]
Thank you so much for this mate. Is it possible for you to provide the same sorting options for xvideos.com also?

**Comment by kuwanishi** [comment]
At the moment the filters depend on the ability of the site to provide them. Xhamster has filters for quality and duration, so they can be easily added to the addon. As fas as I can tell xvideos does not. It could still be possible to filter the listings in the addon, rather than depending on the site to do it, but as far as I know that is not currently done for any site.

**Comment by imurreflection** [comment]
Yes, you are correct. Filter options are available only after search. Sorry about this request.

**Pull request merged**
