### PR TITLE
updated viralvideosx, daftsex, streamate

### PR DESCRIPTION
**Pull request by 12asdfg12**
viralvideosx, replaced by viralvideosporno, fixed + added link selector (some hosts requires real-debrid)
daftsex, updated server lists
streamate fixed

### CODE REVIEW

**Comment by felsandric** [comment]
Thanks super appreciate it for excellent support. Thanks Dobbelina and Team. Can you please look into fixing search so you can search for fav model
On SM.

**Comment by 12asdfg12** [comment]
search fixed

**Comment by felsandric** [comment]
I don’t know why search brings me to same page. When I click on search and search for model. It doesn’t search still updated add on as well.

**Comment by 12asdfg12** [comment]
When you search for a model, if found, the model is added to favorites. This is how it was implemented, i just fix the functionality.

**Pull request merged**
