### PR TITLE
Update aagmaal.py

### PR DESCRIPTION
**Pull request by disha9551**
Aagmaal site change to aagmaal.site

### CODE REVIEW

**Comment by dobbelina** [comment]
@Gujal00 @12asdfg12 @ErosVece
Thanks for the contribution.
It fixes the thumbnails but links don't play, needs further fixing.

**Comment by Gujal00** [comment]
this is a different site to what we have in cumination. Will post the proper thumbnail fix for the one in the addon

**Comment by DJMix-I-Can** [comment]
The new site is aagmaal.click not aagmaal.site. The videos would still play without having the thumbnails in the directory BUT when you go to the categories, it won't. As @dobbelina stated, it needs more tweaking.

**Comment by dobbelina** [comment]
Closing this pull request, proper fix has been merged https://github.com/dobbelina/repository.dobbelina/commit/452e68a1916c3c25b06d9a7331e288791c04f5d2

**Pull request closed without merging**
